version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "nasud2198vsd2dv"
      PGDATA: "/var/lib/postgresql@17/data/pgdata"
    volumes:
      - ../db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql@17/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d maindb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    links:
      - postgres:postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "plem56rus@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "nasud2198vsd2dv"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    container_name: kafka
    image: bitnami/kafka:2.3.1-ol-7-r61
    restart: on-failure
    links:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CFG_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_CFG_ADVERTISED_PORT: '9092'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_MESSAGE_MAX_BYTES: '200000000'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,SASL_PLAINTEXT://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: 'kafka.security.auth.SimpleAclAuthorizer'
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_INTER_BROKER_USER: adminplain
      KAFKA_INTER_BROKER_PASSWORD: admin-secret
      KAFKA_BROKER_USER: adminplain
      KAFKA_BROKER_PASSWORD: admin-secret
      ALLOW_PLAINTEXT_LISTENER: yes

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge